name: CI/CD

on:
  push:
  schedule:
  - cron:  '1 0 * * *'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag pythia-python:$GITHUB_SHA --compress
        docker images
