name: CI/CD

on:
  push:
  schedule:
  - cron:  '1 0 * * *'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag pythia-python:$GITHUB_SHA --compress
        docker images
    - name: Run test program
      run: |
        docker run --rm -v $PWD:$PWD -w $PWD pythia-python:$GITHUB_SHA -c "python tests/main01.py > main01_out.txt"
        wc main01_out.txt
