name: CI/CD

on:
  push:
  pull_request:
  schedule:
  - cron:  '1 0 * * 0'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build Docker image
      if: "!(startsWith(github.ref, 'refs/tags/'))"
      uses: docker/build-push-action@v1
      with:
        repository: matthewfeickert/pythia-python
        dockerfile: Dockerfile
        tags: test
        tag_with_sha: true
        tag_with_ref: true
        push: false
    - name: List Built Images
      run: docker images
    - name: Run test program in C++
      run: >-
        docker run --rm
        --user $(id --user $USER):$(id --group)
        --volume $PWD:/home/docker/work
        matthewfeickert/pythia-python:test
        'g++ tests/main01.cc -pthread -o tests/main01 $(pythia8-config --cxxflags --ldflags); ./tests/main01 > main01_out_cpp.txt';
        wc main01_out_cpp.txt
    - name: Run test program in Python
      run: >-
        docker run --rm
        --user $(id --user $USER):$(id --group)
        --volume $PWD:/home/docker/work
        matthewfeickert/pythia-python:test
        "python tests/main01.py > main01_out_py.txt";
        wc main01_out_py.txt

    - name: Test HepMC3
      run: >-
        docker run --rm
        --user $(id --user $USER):$(id --group)
        --volume $PWD:/home/docker/work
        matthewfeickert/pythia-python:test
        'g++ tests/main300.cc -pthread -o tests/main300 $(pythia8-config --cxxflags --ldflags) -lHepMC3; ./tests/main300 --input main300.cmnd --hepmc_output main300.hepmc'
        wc main300.hepmc

    - name: Test LHAPDF CLI
      run: >-
        docker run --rm
        matthewfeickert/pythia-python:test
        "lhapdf install CT10nlo"

    - name: Test FastJet
      run: >-
        docker run --rm
        --user $(id --user $USER):$(id --group)
        --volume $PWD:/home/docker/work
        matthewfeickert/pythia-python:test
        'g++ tests/test_FastJet.cc -o tests/test_FastJet $(fastjet-config --cxxflags --libs --plugins); ./tests/test_FastJet'

    - name: Test FastJet Python
      run: >-
        docker run --rm
        --user $(id --user $USER):$(id --group)
        --volume $PWD:/home/docker/work
        matthewfeickert/pythia-python:test
        "python tests/test_FastJet.py"

    - name: Test Python imports
      run: >-
        docker run --rm
        --user $(id --user $USER):$(id --group)
        --volume $PWD:/home/docker/work
        matthewfeickert/pythia-python:test
        "python -m pip install --upgrade pytest; pytest --verbose tests"
