name: CI/CD

on:
  push:
  pull_request:
  schedule:
  - cron:  '1 0 * * 0'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build Docker image
      if: "!(startsWith(github.ref, 'refs/tags/'))"
      uses: docker/build-push-action@v1
      with:
        repository: matthewfeickert/pythia-python
        dockerfile: Dockerfile
        tags: test
        tag_with_sha: true
        tag_with_ref: true
        push: false
    - name: List Built Images
      run: docker images
    - name: Run test program in C++
      run: >-
        docker run --rm
        -v $PWD:$PWD
        -w $PWD
        matthewfeickert/pythia-python:test
        "g++ tests/main01.cc -o tests/main01 -lpythia8 -ldl; ./tests/main01 > main01_out_cpp.txt";
        wc main01_out_cpp.txt
    - name: Run test program in Python
      run: >-
        docker run --rm
        -v $PWD:$PWD
        -w $PWD
        matthewfeickert/pythia-python:test
        "python tests/main01.py > main01_out_py.txt";
        wc main01_out_py.txt
    - name: Test HepMC
      run: >-
        docker run --rm
        -v $PWD:$PWD
        -w $PWD
        matthewfeickert/pythia-python:test
        "g++ tests/main42.cc -o tests/main42 -lpythia8 -lHepMC -ldl; ./tests/main42 tests/main42.cmnd main42_out.hepmc"
        wc main42_out.hepmc
    - name: Test LHAPDF CLI
      run: >-
        docker run --rm
        matthewfeickert/pythia-python:test
        "lhapdf install CT10nlo"
    - name: Test FastJet
      run: >-
        docker run --rm
        -v $PWD:$PWD
        -w $PWD
        matthewfeickert/pythia-python:test
        "g++ tests/test_FastJet.cc -o tests/test_FastJet \$(/usr/local/venv/bin/fastjet-config --cxxflags --libs --plugins); ./tests/test_FastJet"
    - name: Test FastJet Python
      run: >-
        docker run --rm
        -v $PWD:$PWD
        -w $PWD
        matthewfeickert/pythia-python:test
        "python tests/test_FastJet.py"
