name: Publish Docker Images

on:
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  build-and-publish:
    name: Build and publish Docker images to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build and Publish to Registry
      if: "!(startsWith(github.ref, 'refs/tags/'))"
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: matthewfeickert/pythia-python
        dockerfile: Dockerfile
        tags: latest,pythia8.303,pythia8.303-hepmc2.06.11-fastjet3.3.4-python3.9
    - name: Build and Publish to Registry with Release Tag
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: matthewfeickert/pythia-python
        dockerfile: Dockerfile
        tags: latest,latest-stable,pythia8.303,pythia8.303-hepmc2.06.11-fastjet3.3.4-python3.9
        tag_with_ref: true
